name: Build and Deploy fuwari

on:
  push:
    branches: [ main ]   # 每次推 main 分支触发
  workflow_dispatch:      # 也可以手动触发

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 拉取仓库
      - name: Checkout
        uses: actions/checkout@v4

      # 2. 设置 Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. 安装依赖（pnpm）
      - name: Install dependencies with pnpm
        run: |
          corepack enable
          corepack prepare pnpm@latest --activate
          pnpm install

      # 4. 构建项目
      - name: Build
        run: pnpm build

      # 5. 防止 GitHub Pages 使用 Jekyll
      - name: Add .nojekyll
        run: touch dist/.nojekyll

      # 6. 部署到 GitHub Pages（强制覆盖 gh-pages）
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          force_orphan: true      # 强制使用孤立分支覆盖
          enable_jekyll: false
          keep_files: false
